# Site Settings
title: Snippets
email: kjlarson1@outlook.com
description: >
  Code Snippets
baseurl: "/snippets"
url: "http://kjlarson.github.io"
twitter_username: 
github_username:  KJLarson
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
categories: [git, terminal, javascript, html, css]
kramdown:
  input: GFM
