# Site Settings
title: Snippets
email: kjlarson1@outlook.com
description: >
  Code Snippets
baseurl: ""
url: "http://localhost:4000"
twitter_username: 
github_username:  KJLarson
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
categories: [basics, data types, conditionals, operators, loops, functions]
kramdown:
  input: GFM