# Site Settings
title: JS Reference
email: taniarascia@gmail.com
description: >
  JavaScript reference
baseurl: "/js"
url: "http://taniarascia.github.io"
twitter_username: taniarascia
github_username:  taniarascia
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
categories: [basics, data types, conditionals, operators, loops, functions]
kramdown:
  input: GFM